# Setup
title: "Mathematica 激活指南"
tagline: "Mathematica 的安装、激活、入门、常见问题"
baseurl: ""
paginate: 1
locale: "zh-hans"

# Contact
author:
  name: "TieBaMma"
  url: "https://github.com/TieBaMma"
repourl: "https://github.com/TieBaMma/InstallTutorial"

# Gems
gems:
  - jekyll-paginate

# Markdown options
markdown: kramdown

# Others
exclude: [".github/", ".vscode/", "docs/", "Gemfile", "README.md"]
